spring:
  profiles: pfsdevoauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dn47gh3y
    maximum-pool-size: 40
    url: jdbc:mysql://localhost:3306/pfsriskmodel?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    validation-query: select 1
    connection-test-query: select 1
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 60000
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true

  activiti:
    mail-server-host: smtp.gmail.com
    mail-server-port: 587
    mail-server-user-name: pfsriskmodel@gmail.com
    mail-server-password: Sapsap@123
    mail-server-default-from: pfsriskmodel@gmail.com
    mail-server-use-tls: true
security:
  oauth2:
    client:
      client-id: pfs-client
      client-secret: pfs-secret
      access-token-uri: http://192.168.1.246:9999/auth/oauth/token
      user-authorization-uri: http://192.168.1.246:9999/auth/oauth/authorize
    resource:
      userInfoUri: http://192.168.1.203:9999/auth/api/me
lmsEnquiry:
  baseUrl: http://192.168.1.246:8080/enquiry
sap:
  postUrl: http://192.168.1.203:8000/sap/opu/odata/sap/ZPFS_RISK_MODEL_EVALUATION_SRV/RiskEvaluationSet?sap-client=300
  userName: sajeev
  password: sapsap
server:
  port: 8090